### ISSUE TITLE
Frechet distance was unable to be found

### ISSUE THREAD

**Issue by ratnanil** [christiankrahenbuhl/CMA-week3#1]
https://github.com/christiankrahenbuhl/CMA-week3/blob/737eb483d66bdb05b6b4a3f958ce361e2fb33d2f/week3-rexercise.R#L117-L118<br/><br/>You encouter the same error as https://github.com/dionisanderegg/cma-week3/issues/1 but I dont understand the reason behind this. If one of you finds out, please report!

**Comment by christiankrahenbuhl** [comment]
Will do!
